FROM debian:latest

USER root

ENV HTTPS_PROXY=false
ENV HTTP_PROXY=false

RUN mkdir -p /opt/java
WORKDIR /opt/java
RUN apt-get update  \
	&& apt-get install wget -y

ADD ./ressources/wget_proxy_setup.sh /opt/wget_proxy_setup.sh
RUN chmod +x /opt/wget_proxy_setup.sh

RUN /opt/wget_proxy_setup.sh

#RUN wget https://github.com/gaochaung/SHRINEfile/raw/master/jdk-8u192-linux-x64.tar.gz \
#	&& tar xzf jdk-8u192-linux-x64.tar.gz
ADD ./ressources/jdk-8u192-linux-x64.tar.gz /opt/java/jdk-8u192-linux-x64.tar.gz
#RUN tar xzf /opt/java/jdk-8u192-linux-x64.tar.gz -C /opt/java


RUN mv /opt/java/jdk-8u192-linux-x64.tar.gz/jdk1.8.0_192 /opt/java

RUN chown -R root: jdk1.8.0_*

#-- for JAVA (in case you have another version of Java installed)
RUN 	update-alternatives --install /usr/bin/java java /opt/java/jdk1.8.0_192/bin/java 1 \
#-- for JAR (in case you have another version of Java installed)
	&& 	update-alternatives --install /usr/bin/jar jar /opt/java/jdk1.8.0_192/bin/jar 1 \
#-- for JAVAC (in case you have another version of Java installed)
	&& 	update-alternatives --install /usr/bin/javac javac /opt/java/jdk1.8.0_192/bin/javac 1 \
	&&	update-alternatives --config javac

#-- setting JAVA variables
RUN 	export JAVA_HOME=/opt/java/jdk1.8.0_192 \
	&& 	export JRE_HOME=/opt/java/jdk1.8.0_192/jre \
	&&	export PATH=$PATH:/opt/java/jdk1.8.0_192/bin:/opt/java/jdk1.8.0_192/jre/bin

# ENV KEYSTORE_ALIAS=$KEYSTORE_ALIAS
# ENV KEYSTORE_HUMAN=$KEYSTORE_HUMAN
# ENV KEYSTORE_CITY=$KEYSTORE_CITY
# ENV KEYSTORE_STATE=$KEYSTORE_STATE
# ENV KEYSTORE_COUNTRY=$KEYSTORE_COUNTRY
# ENV KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD
# ENV KEYSTORE_FILE=$KEYSTORE_FILE
#
# ENV SHRINE_HOST=$SHRINE_HOST
# ENV SHRINE_PORT=$SHRINE_PORT
# ENV SHRINE_WEBCLIENT_HOST=SHRINE_WEBCLIENT_HOST
# ENV SHRINE_WEBCLIENT_PORT=SHRINE_WEBCLIENT_HOST
#
# ENV SHRINE_HUB_HOST=$SHRINE_HUB_HOST
# ENV SHRINE_HUB_PORT=$SHRINE_HUB_PORT
#
# ENV SHRINE_DB_HOST=$SHRINE_DB_HOST
# ENV SHRINE_DB_PORT=$SHRINE_DB_PORT
# ENV MYSQL_USER=$MYSQL_USER
# ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
#
# ENV NODE_NAME=$NODE_NAME
#
# ENV PM_HOST=$PM_HOST
# ENV PM_PORT=$PM_PORT
# ENV ONT_HOST=$ONT_HOST
# ENV ONT_PORT=$ONT_PORT
# ENV CRC_HOST=$CRC_HOST
# ENV CRC_PORT=$CRC_PORT
#
# ENV I2B2_DOMAIN=$I2B2_DOMAIN
# ENV I2B2_USER=$I2B2_USER
# ENV I2B2_PASSWORD=$I2B2_PASSWORD
# ENV I2B2_CRC_PROJECT_ID=$I2B2_CRC_PROJECT_ID
# ENV SHRINE_ONT_PROJECT_ID=$SHRINE_ONT_PROJECT_ID
#
 	ENV QEP_USER=qep
# ENV QEP_PASSWORD=$QEP_PASSWORD
#
# ENV IS_HUB=$IS_HUB

RUN	apt-get install -y postfix -y\
	&& 	apt-get install -y ntp -y \
	&& 	apt-get install unzip -y \
	&&	apt-get install vim -y

RUN apt-get install systemd -y


RUN mkdir -p /opt/shrine/tomcat

RUN 	wget https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.28/bin/apache-tomcat-8.5.28.tar.gz \
	&&	tar xvf apache-tomcat-8.5.28.tar.gz -C /opt/shrine/tomcat --strip-components=1
ADD ./ressources/AdapterMappings.csv /opt/shrine/tomcat/lib/AdapterMappings.csv


	
